project_id = "zbiuxfglgyapypislkhv"

[functions.fetch-openai-models]
verify_jwt = false

[functions.generate-report]
verify_jwt = true

[functions.parse-kb-document]
verify_jwt = true

[functions.review-report]
verify_jwt = true